# Generated by Django 3.0.2 on 2020-02-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmuser',
            name='level',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=8, verbose_name='등급'),
            preserve_default=False,
        ),
    ]
