# Generated by Django 3.0.2 on 2020-01-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': '패캠사용', 'verbose_name_plural': '패캠사용자'},
        ),
        migrations.AddField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(default='test', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
